name = "linkup-auth-bot"
main = "src/index.js"
compatibility_date = "2026-05-20"

[vars]
SUPABASE_URL = "https://ryaxynjczfwqyqvpmorl.supabase.co"

[observability]
enabled = true
head_sampling_rate = 1