import React, { useState, useEffect, useRef } from 'react';
import { supabase, usePlatform } from '@linkup-platform/sdk-core';
import AvatarCropperModal from '../../src/core/components/AvatarCropperModal.jsx';
import './GroupChat.css';

const GroupInfoPanel = ({ chatInfo, conversationId, currentUser, members, setMembers, messages, myRole, onClose, onUpdateInfo, onDisband }) => {
    const [activeTab, setActiveTab] = useState('members');
    const [mediaSubTab, setMediaSubTab] = useState('media'); // files, media, links
    
    const [selectedFile, setSelectedFile] = useState(null);
    const [croppedAvatar, setCroppedAvatar] = useState(null);
    const fileInputRef = useRef(null);
    
    const [editTitle, setEditTitle] = useState(chatInfo.title || '');
    const [nameStatus, setNameStatus] = useState('idle'); // idle, saving, success, error
    const [nameError, setNameError] = useState('');
    const [editSlug, setEditSlug] = useState(chatInfo.metadata?.slug || '');
    const [slugStatus, setSlugStatus] = useState('idle'); // idle, saving, success, error
    const [slugError, setSlugError] = useState('');
    const [editPrivacy, setEditPrivacy] = useState(chatInfo.metadata?.privacy || 'public');
    const [isSaving, setIsSaving] = useState(false);
    const [alertNotice, setAlertNotice] = useState(null); // Replaces window.alert
    const [avatarError, setAvatarError] = useState(false);

    // Sync state if chatInfo metadata updates after initial mount
    useEffect(() => {
        setEditTitle(chatInfo.title || '');
        setEditSlug(chatInfo.metadata?.slug || '');
        setEditPrivacy(chatInfo.metadata?.privacy || 'public');
    }, [chatInfo.title, chatInfo.metadata]);

    // Reset avatar error state if the avatar URL actually changes
    useEffect(() => setAvatarError(false), [croppedAvatar, chatInfo.avatar_url]);

    // Menus & Modals
    const [showOptions, setShowOptions] = useState(false);
    const [showAddMember, setShowAddMember] = useState(false);
    const [inviteContacts, setInviteContacts] = useState([]);
    const [confirmAddUser, setConfirmAddUser] = useState(null);
    const [privacyModal, setPrivacyModal] = useState(false);
    const [tempPrivacy, setTempPrivacy] = useState(editPrivacy);
    const [inviteCopied, setInviteCopied] = useState(false);

    const [activeMemberMenu, setActiveMemberMenu] = useState(null);
    const [confirmModal, setConfirmModal] = useState(null);
    const [disbandModal, setDisbandModal] = useState(false);
    const [disbandInput, setDisbandInput] = useState('');
    const [punishConfig, setPunishConfig] = useState(null);

    // Auto-scrape Media Assets from Messages
    const mediaAssets = messages.flatMap(m => m.attachments ? m.attachments.filter(a => a.type.startsWith('image/') || a.type.startsWith('video/')) : []);
    const docFiles = messages.flatMap(m => m.attachments ? m.attachments.filter(a => !a.type.startsWith('image/') && !a.type.startsWith('video/')) : []);
    const sharedLinks = messages.flatMap(m => {
        if (!m.text) return [];
        const urls = m.text.match(/(https?:\/\/[^\s]+)/g) || [];
        return urls.map(url => ({ url, sender: members[m.sender_id]?.name || 'Unknown', time: m.created_at }));
    });

    // Strict DB truth. No front-end guessing.
    const squadHandle = chatInfo.metadata?.slug;
    
    let rawBase = window.location.origin + window.location.pathname;
    // Fix for Blob URLs generated by the IDE Preview environment
    if (window.location.href.startsWith('blob:')) {
        try { 
            rawBase = window.top.location.origin + window.top.location.pathname; 
        } catch (e) { 
            rawBase = window.location.origin + '/'; 
        }
    }
    const cleanBase = rawBase.split('?')[0].replace(/\/$/, '');
    
    const inviteLink = squadHandle ? `${cleanBase}?sq=${squadHandle}` : 'Fetching invitation link...';

    const isPublic = !chatInfo.metadata?.privacy || chatInfo.metadata.privacy === 'public';

    const handleCopyInvite = () => {
        navigator.clipboard.writeText(inviteLink);
        setInviteCopied(true);
        setTimeout(() => setInviteCopied(false), 2000);
    };

    // Fetch DM contacts for "Add Member" screen
    useEffect(() => {
        if (showAddMember) {
            supabase.rpc('get_user_conversations', { req_user_id: currentUser.id }).then(({data}) => {
                if (data) {
                    const contacts = data.filter(c => c.type === 'dm' && !members[c.other_user_id]);
                    setInviteContacts(contacts);
                }
            });
        }
    }, [showAddMember, currentUser.id, members]);

    const executeAddMember = async () => {
        if (!confirmAddUser) return;
        await supabase.from('conversation_members').insert({
            conversation_id: conversationId, user_id: confirmAddUser.other_user_id, role: 'member'
        });
        setMembers(prev => ({
            ...prev,
            [confirmAddUser.other_user_id]: { role: 'member', name: confirmAddUser.other_user_name, avatar: confirmAddUser.other_user_avatar }
        }));
        setConfirmAddUser(null);
        setShowAddMember(false);
    };

    const updateSquadPrivacy = async (val) => {
        const newMeta = { ...chatInfo.metadata, privacy: val };
        const { data: updatedRows, error } = await supabase
            .from('conversations')
            .update({ metadata: newMeta })
            .eq('id', conversationId)
            .select();
            
        if (error || !updatedRows || updatedRows.length === 0) {
            setAlertNotice("Permission denied. You are not authorized to update this group's settings.");
            setPrivacyModal(false);
            return;
        }
        
        onUpdateInfo({ ...chatInfo, metadata: newMeta });
        setEditPrivacy(val);
        setPrivacyModal(false);
    };

    const updateSquadName = async () => {
        if (!editTitle.trim() || editTitle === chatInfo.title) return;
        
        setNameStatus('saving');
        const { data: updatedRows, error } = await supabase
            .from('conversations')
            .update({ title: editTitle })
            .eq('id', conversationId)
            .select();
            
        if (error || !updatedRows || updatedRows.length === 0) {
            setNameStatus('error');
            setNameError("Permission denied.");
            setEditTitle(chatInfo.title); // Revert UI
            return;
        }
        
        onUpdateInfo({ ...chatInfo, title: editTitle });
        setNameStatus('success');
        setTimeout(() => setNameStatus('idle'), 3000);
    };

    const updateSquadSlug = async () => {
        const cleanSlug = editSlug.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (!cleanSlug || cleanSlug === chatInfo.metadata?.slug) return;
        
        setSlugStatus('saving');

        // 1. Manually enforce uniqueness across the JSONB column
        const { data: existing } = await supabase
            .from('conversations')
            .select('id')
            .contains('metadata', { slug: cleanSlug })
            .neq('id', conversationId)
            .maybeSingle();

        if (existing) {
            setSlugStatus('error');
            setSlugError("Handle is already taken by another group.");
            return;
        }

        // 2. Perform Update and force response data to verify RLS success
        const newMeta = { ...chatInfo.metadata, slug: cleanSlug };
        const { data: updatedRows, error } = await supabase
            .from('conversations')
            .update({ metadata: newMeta })
            .eq('id', conversationId)
            .select();
        
        if (error || !updatedRows || updatedRows.length === 0) {
            setSlugStatus('error');
            setSlugError("Permission denied. Update rejected.");
            setEditSlug(chatInfo.metadata?.slug || ''); // Revert UI to truth
            return;
        }

        onUpdateInfo({ ...chatInfo, metadata: newMeta });
        setEditSlug(cleanSlug);
        setSlugStatus('success');
        setTimeout(() => setSlugStatus('idle'), 3000);
    };

    const handleAvatarUpdate = async (blob) => {
        const url = URL.createObjectURL(blob);
        setCroppedAvatar({ blob, url });
        setSelectedFile(null);

        // Auto-upload and save avatar immediately
        setIsSaving(true);
        const arrayBuffer = await blob.arrayBuffer();
        const filePath = `group_avatars/${conversationId}/avatar_${Date.now()}.png`;
        await supabase.storage.from('chat_media').upload(filePath, arrayBuffer, { contentType: 'image/png', upsert: true });
        const { data: { publicUrl } } = supabase.storage.from('chat_media').getPublicUrl(filePath);
        
        await supabase.from('conversations').update({ avatar_url: publicUrl }).eq('id', conversationId);
        onUpdateInfo({ ...chatInfo, avatar_url: publicUrl });
        setIsSaving(false);
        setCroppedAvatar(null);
    };

    const executeKick = async (uid) => {
        setConfirmModal(null);
        await supabase.rpc('squad_kick_member', { req_conv_id: conversationId, req_target_id: uid, req_admin_id: currentUser.id });
        setMembers(prev => {
            const next = { ...prev };
            delete next[uid];
            return next;
        });
    };

    const executePunishment = async () => {
        const { uid, type, isTemp, duration, unit } = punishConfig;
        
        let until = null;
        if (isTemp) {
            const safeDuration = duration === '' || isNaN(duration) ? 1 : duration;
            const multipliers = { minutes: 60000, hours: 3600000, days: 86400000, weeks: 604800000, months: 2592000000 };
            const ms = safeDuration * multipliers[unit];
            until = new Date(Date.now() + ms).toISOString();
        } else {
            // For permanent mute, set a date 100 years in the future. For ban, null means permanent.
            until = type === 'mute' ? new Date(Date.now() + 3153600000000).toISOString() : null;
        }

        if (type === 'ban') {
            await supabase.rpc('squad_ban_member', { req_conv_id: conversationId, req_target_id: uid, req_admin_id: currentUser.id, req_banned_until: until });
            setMembers(prev => {
                const next = { ...prev };
                delete next[uid];
                return next;
            });
        } else {
            await supabase.rpc('squad_mute_member', { req_conv_id: conversationId, req_target_id: uid, req_admin_id: currentUser.id, req_muted_until: until });
        }
        setPunishConfig(null);
    };

    const executeDisband = async () => {
        if (disbandInput !== chatInfo.title) return;
        await supabase.from('conversations').delete().eq('id', conversationId);
        onDisband();
    };

    const displayAvatar = croppedAvatar?.url || chatInfo.avatar_url;

    return (
        <div className="si-overlay" onClick={() => { setActiveMemberMenu(null); setShowOptions(false); }}>
            {selectedFile && (
                <AvatarCropperModal 
                    imageFile={selectedFile} 
                    onCancel={() => setSelectedFile(null)} 
                    onSave={handleAvatarUpdate}
                />
            )}
            <div className="si-sheet" onClick={(e) => { e.stopPropagation(); setShowOptions(false); setActiveMemberMenu(null); }}>
                <div className="si-hero">
                    <button className="si-back" onClick={onClose}><i className="fas fa-chevron-left"></i></button>
                    <div className="si-options-wrapper">
                        <button className="si-options" onClick={(e) => { e.stopPropagation(); setShowOptions(!showOptions); setActiveMemberMenu(null); }}><i className="fas fa-ellipsis-v"></i></button>
                        {showOptions && (
                            <div className="si-dropdown-menu" style={{top: '40px', right: '0'}}>
                                <button onClick={() => { setShowOptions(false); setShowAddMember(true); }}><i className="fas fa-user-plus"></i> Add Members</button>
                            </div>
                        )}
                    </div>

                    <input type="file" ref={fileInputRef} style={{ display: 'none' }} accept="image/*" onChange={(e) => {
                        if (e.target.files && e.target.files[0]) setSelectedFile(e.target.files[0]);
                        e.target.value = null;
                    }} />
                    <div className="si-avatar-container" onClick={() => myRole === 'owner' && fileInputRef.current?.click()} style={{cursor: myRole === 'owner' ? 'pointer' : 'default'}}>
                        <div className="si-avatar">
                            {displayAvatar && !avatarError ? <img src={displayAvatar} alt="Squad" onError={() => setAvatarError(true)} /> : <i className="fas fa-users"></i>}
                        </div>
                        {myRole === 'owner' && <div className="si-avatar-edit"><i className="fas fa-pencil"></i></div>}
                    </div>
                    <h2 className="si-title">{chatInfo.title}</h2>
                    <div className="si-ppn">#{conversationId.substring(0,8).toUpperCase()}</div>
                    <div className="si-badges">
                        <span className={`si-badge ${!isPublic ? 'private' : 'public'}`}>
                            <i className={`fas fa-${!isPublic ? 'lock' : 'globe'}`}></i> {!isPublic ? 'private' : 'public'}
                        </span>
                        {chatInfo.metadata?.focus && (
                            <span className="si-badge" style={{background: 'rgba(255,255,255,0.1)', color: '#ccc'}}>{chatInfo.metadata.focus}</span>
                        )}
                    </div>

                    {isPublic && (
                        <div className="si-invite-box">
                            <div className="si-invite-url">{inviteLink}</div>
                            <button className="si-invite-copy-btn" onClick={handleCopyInvite}>
                                {inviteCopied ? <i className="fas fa-check"></i> : <i className="fas fa-copy"></i>}
                            </button>
                        </div>
                    )}
                </div>

                <div className="si-tabs">
                    <div className={`si-tab ${activeTab === 'members' ? 'active' : ''}`} onClick={() => setActiveTab('members')}>Members</div>
                    <div className={`si-tab ${activeTab === 'media' ? 'active' : ''}`} onClick={() => setActiveTab('media')}>Media</div>
                    {myRole === 'owner' && <div className={`si-tab ${activeTab === 'settings' ? 'active' : ''}`} onClick={() => setActiveTab('settings')}>Control Panel</div>}
                </div>

                <div className="si-body">
                    {activeTab === 'members' && (
                        <div className="si-directory">
                            {Object.entries(members).map(([uid, m]) => (
                                <div className="si-member-row" key={uid}>
                                    <img src={m.avatar || 'https://via.placeholder.com/150'} alt="Avatar" className="si-member-avatar" />
                                    <div className="si-member-info">
                                        <div className="si-member-name">
                                            {m.name} {uid === currentUser.id && <span style={{fontSize:'0.7rem', color:'#888'}}>(You)</span>}
                                        </div>
                                        <span className={`si-member-role ${m.role === 'owner' ? 'si-role-owner' : 'si-role-member'}`}>{m.role}</span>
                                    </div>
                                    {myRole === 'owner' && uid !== currentUser.id && (
                                        <div className="si-member-actions" style={{ position: 'relative' }}>
                                            <button className="si-action-btn" onClick={(e) => { e.stopPropagation(); setActiveMemberMenu(activeMemberMenu === uid ? null : uid); }}>
                                                <i className="fas fa-ellipsis-v"></i>
                                            </button>
                                            {activeMemberMenu === uid && (
                                                <div className="si-dropdown-menu" onClick={e => e.stopPropagation()}>
                                                    <button onClick={() => { setActiveMemberMenu(null); setConfirmModal({ uid, name: m.name }); }}>
                                                        <i className="fas fa-user-minus"></i> Kick User
                                                    </button>
                                                    <button onClick={() => { setActiveMemberMenu(null); setPunishConfig({ uid, type: 'mute', isTemp: true, duration: 1, unit: 'days' }); }}>
                                                        <i className="fas fa-comment-slash"></i> Restrict Writing
                                                    </button>
                                                    <button className="danger" onClick={() => { setActiveMemberMenu(null); setPunishConfig({ uid, type: 'ban', isTemp: true, duration: 1, unit: 'days' }); }}>
                                                        <i className="fas fa-ban"></i> Ban User
                                                    </button>
                                                </div>
                                            )}
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    )}

                    {activeTab === 'media' && (
                        <div className="si-vault">
                            <div className="si-media-pills">
                                <div className={`si-media-pill ${mediaSubTab === 'media' ? 'active' : ''}`} onClick={() => setMediaSubTab('media')}>Media</div>
                                <div className={`si-media-pill ${mediaSubTab === 'files' ? 'active' : ''}`} onClick={() => setMediaSubTab('files')}>Files</div>
                                <div className={`si-media-pill ${mediaSubTab === 'links' ? 'active' : ''}`} onClick={() => setMediaSubTab('links')}>Links</div>
                            </div>

                            <div className="si-media-content">
                                {mediaSubTab === 'media' && (
                                    mediaAssets.length > 0 ? (
                                        <div className="si-media-grid">
                                            {mediaAssets.map((m, i) => (
                                                <a href={m.url} target="_blank" rel="noopener noreferrer" className="si-media-thumb" key={i}>
                                                    <img src={m.url} alt="Media" />
                                                </a>
                                            ))}
                                        </div>
                                    ) : <div className="si-vault-empty"><i className="fas fa-image"></i><p>No photos or videos yet.</p></div>
                                )}

                                {mediaSubTab === 'files' && (
                                    docFiles.length > 0 ? (
                                        <div style={{display:'flex', flexDirection:'column', gap:'8px'}}>
                                            {docFiles.map((f, i) => (
                                                <a href={f.url} target="_blank" rel="noopener noreferrer" className="si-vault-item" key={i}>
                                                    <div className="si-vault-icon"><i className="fas fa-file-pdf"></i></div>
                                                    <div className="si-vault-info">
                                                        <div className="si-vault-name">{f.name}</div>
                                                        <div className="si-vault-meta">{(f.size / 1024 / 1024).toFixed(2)} MB</div>
                                                    </div>
                                                </a>
                                            ))}
                                        </div>
                                    ) : <div className="si-vault-empty"><i className="fas fa-file-alt"></i><p>No documents shared yet.</p></div>
                                )}

                                {mediaSubTab === 'links' && (
                                    sharedLinks.length > 0 ? (
                                        <div style={{display:'flex', flexDirection:'column', gap:'8px'}}>
                                            {sharedLinks.map((l, i) => (
                                                <a href={l.url} target="_blank" rel="noopener noreferrer" className="si-vault-item" key={i}>
                                                    <div className="si-vault-icon link"><i className="fas fa-link"></i></div>
                                                    <div className="si-vault-info">
                                                        <div className="si-vault-name link">{l.url}</div>
                                                        <div className="si-vault-meta">From {l.sender}</div>
                                                    </div>
                                                </a>
                                            ))}
                                        </div>
                                    ) : <div className="si-vault-empty"><i className="fas fa-link"></i><p>No links shared yet.</p></div>
                                )}
                            </div>
                        </div>
                    )}

                    {activeTab === 'settings' && myRole === 'owner' && (
                        <div className="si-settings">
                            <div className="si-settings-group">
                                <label className="si-label">Group Name</label>
                                <div className="si-input-wrapper">
                                    <input 
                                        type="text" 
                                        className="si-input" 
                                        value={editTitle} 
                                        onChange={e => { setEditTitle(e.target.value); setNameStatus('idle'); }} 
                                        onKeyPress={e => e.key === 'Enter' && updateSquadName()}
                                    />
                                </div>
                                {(editTitle !== chatInfo.title || nameStatus !== 'idle') && (
                                    <div style={{ marginTop: '10px', display: 'flex', alignItems: 'center', gap: '10px', minHeight: '30px' }}>
                                        {editTitle !== chatInfo.title && (
                                            <button className="si-save-slug-btn" onClick={updateSquadName} disabled={nameStatus === 'saving' || !editTitle.trim()}>
                                                {nameStatus === 'saving' ? 'Saving...' : 'Save Name'}
                                            </button>
                                        )}
                                        {nameStatus === 'error' && <span style={{ color: '#ff5f5f', fontSize: '0.8rem' }}><i className="fas fa-exclamation-triangle"></i> {nameError}</span>}
                                        {nameStatus === 'success' && <span style={{ color: '#42d7b8', fontSize: '0.8rem', animation: 'fadeIn 0.3s ease' }}><i className="fas fa-check-circle"></i> Name updated!</span>}
                                    </div>
                                )}
                            </div>

                            <div className="si-settings-group">
                                <label className="si-label">Group Link Handle</label>
                                <div className="si-slug-container">
                                    <span className="si-slug-prefix">{cleanBase}?sq=</span>
                                    <input 
                                        type="text" 
                                        className="si-slug-input" 
                                        value={editSlug} 
                                        onChange={e => { setEditSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]/g, '')); setSlugStatus('idle'); }} 
                                        onKeyPress={e => e.key === 'Enter' && updateSquadSlug()}
                                    />
                                </div>
                                {(editSlug !== (chatInfo.metadata?.slug || '') || slugStatus !== 'idle') && (
                                    <div style={{ marginTop: '10px', display: 'flex', alignItems: 'center', gap: '10px', minHeight: '30px' }}>
                                        {editSlug !== (chatInfo.metadata?.slug || '') && (
                                            <button className="si-save-slug-btn" onClick={updateSquadSlug} disabled={slugStatus === 'saving' || !editSlug.trim()}>
                                                {slugStatus === 'saving' ? 'Saving...' : 'Save Handle'}
                                            </button>
                                        )}
                                        {slugStatus === 'error' && <span style={{ color: '#ff5f5f', fontSize: '0.8rem' }}><i className="fas fa-exclamation-triangle"></i> {slugError}</span>}
                                        {slugStatus === 'success' && <span style={{ color: '#42d7b8', fontSize: '0.8rem', animation: 'fadeIn 0.3s ease' }}><i className="fas fa-check-circle"></i> Handle updated!</span>}
                                    </div>
                                )}
                            </div>

                            <div className="si-settings-row" onClick={() => setPrivacyModal(true)}>
                                <div className="sr-info">
                                    <h4>Privacy Status</h4>
                                    <p>{chatInfo.metadata?.privacy === 'public' ? 'Anyone can find and join' : 'Invite only'}</p>
                                </div>
                                <div className="sr-val">{chatInfo.metadata?.privacy} <i className="fas fa-chevron-right"></i></div>
                            </div>

                            <hr style={{border:'none', borderTop:'1px solid rgba(255,255,255,0.05)', margin:'2rem 0'}}/>

                            <div className="si-settings-group">
                                <label className="si-label" style={{color:'#ff5f5f'}}>Danger Zone</label>
                                <p style={{fontSize:'0.8rem', color:'#888', marginBottom:'1rem'}}>Deleting this group will permanently remove all associated messages, files, and links. This action is irreversible.</p>
                                <button className="si-disband-btn" onClick={() => setDisbandModal(true)}>
                                    <i className="fas fa-triangle-exclamation"></i> Delete Group
                                </button>
                            </div>
                        </div>
                    )}
                </div>
            </div>

            {/* Privacy Configuration Modal */}
            {privacyModal && (
                <div className="custom-modal-overlay">
                    <div className="custom-modal-card">
                        <h3>Squad Privacy</h3>
                        <p>Configure how others discover and join this group.</p>
                        <div className="cm-privacy-options">
                            <div className={`cm-privacy-card ${tempPrivacy === 'public' ? 'active' : ''}`} onClick={() => setTempPrivacy('public')}>
                                <i className="fas fa-globe"></i>
                                <div>
                                    <h4>Public</h4>
                                    <p>Searchable and accessible via Invite Link.</p>
                                </div>
                            </div>
                            <div className={`cm-privacy-card ${tempPrivacy === 'private' ? 'active' : ''}`} onClick={() => setTempPrivacy('private')}>
                                <i className="fas fa-lock"></i>
                                <div>
                                    <h4>Private</h4>
                                    <p>Hidden. Members must be added by Admin.</p>
                                </div>
                            </div>
                        </div>
                        <div className="cm-footer" style={{marginTop: '1rem'}}>
                            <button className="cm-btn-cancel" onClick={() => { setTempPrivacy(chatInfo.metadata?.privacy); setPrivacyModal(false); }}>Cancel</button>
                            <button className="cm-btn-primary" onClick={() => updateSquadPrivacy(tempPrivacy)}>Confirm Status</button>
                        </div>
                    </div>
                </div>
            )}

            {/* Full Screen Add Member Overlay */}
            {showAddMember && (
                <div className="si-fullscreen-overlay">
                    <header className="si-fs-header">
                        <button className="icon-button" onClick={() => setShowAddMember(false)}><i className="fas fa-chevron-left"></i></button>
                        <h2>Add Member</h2>
                        <div style={{width:'36px'}}></div>
                    </header>
                    <div className="si-fs-body">
                        {inviteContacts.length === 0 ? (
                            <div className="si-vault-empty">
                                <i className="fas fa-user-slash"></i>
                                <p>No eligible contacts found in your DMs.</p>
                            </div>
                        ) : (
                            inviteContacts.map(c => (
                                <div className="si-member-row" key={c.other_user_id} style={{cursor:'pointer'}} onClick={() => setConfirmAddUser(c)}>
                                    <img src={c.other_user_avatar || 'https://via.placeholder.com/150'} alt="Avatar" className="si-member-avatar" />
                                    <div className="si-member-info">
                                        <div className="si-member-name">{c.other_user_name}</div>
                                        <span className="si-member-role si-role-member">Contact</span>
                                    </div>
                                    <i className="fas fa-plus" style={{color:'var(--accent-teal)'}}></i>
                                </div>
                            ))
                        )}
                    </div>
                </div>
            )}

            {/* Confirm Add Member Modal */}
            {confirmAddUser && (
                <div className="custom-modal-overlay">
                    <div className="custom-modal-card">
                        <h3>Add to Squad</h3>
                        <p>Add <strong>{confirmAddUser.other_user_name}</strong> to the squad?</p>
                        <div className="cm-footer">
                            <button className="cm-btn-cancel" onClick={() => setConfirmAddUser(null)}>Cancel</button>
                            <button className="cm-btn-primary" onClick={executeAddMember}>Confirm Add</button>
                        </div>
                    </div>
                </div>
            )}

            {/* Custom Kick Confirmation Modal */}
            {confirmModal && (
                <div className="custom-modal-overlay">
                    <div className="custom-modal-card">
                        <h3>Kick Member</h3>
                        <p>Are you sure you want to remove <strong>{confirmModal.name}</strong> from the squad? They can rejoin if the group is public.</p>
                        <div className="cm-footer">
                            <button className="cm-btn-cancel" onClick={() => setConfirmModal(null)}>Cancel</button>
                            <button className="cm-btn-danger" onClick={() => executeKick(confirmModal.uid)}>Kick User</button>
                        </div>
                    </div>
                </div>
            )}

            {/* Custom Ban/Mute Configuration Modal */}
            {punishConfig && (
                <div className="custom-modal-overlay">
                    <div className="custom-modal-card">
                        <h3>{punishConfig.type === 'ban' ? 'Ban Member' : 'Restrict Writing'}</h3>
                        <p>Configure restriction for <strong>{members[punishConfig.uid]?.name}</strong>:</p>
                        
                        <div className="cm-radio-group">
                            <label className="cm-radio-label">
                                <input type="radio" checked={punishConfig.isTemp} onChange={() => setPunishConfig({...punishConfig, isTemp: true})} />
                                Temporary
                            </label>
                            <label className="cm-radio-label">
                                <input type="radio" checked={!punishConfig.isTemp} onChange={() => setPunishConfig({...punishConfig, isTemp: false})} />
                                Permanent
                            </label>
                        </div>

                        {punishConfig.isTemp && (
                            <div className="cm-duration-inputs">
                                <input 
                                    type="number" 
                                    min="1" 
                                    value={punishConfig.duration} 
                                    onChange={e => setPunishConfig({...punishConfig, duration: e.target.value === '' ? '' : parseInt(e.target.value)})} 
                                />
                                <select value={punishConfig.unit} onChange={e => setPunishConfig({...punishConfig, unit: e.target.value})}>
                                    <option value="minutes">Minutes</option>
                                    <option value="hours">Hours</option>
                                    <option value="days">Days</option>
                                    <option value="weeks">Weeks</option>
                                    <option value="months">Months</option>
                                </select>
                            </div>
                        )}

                        <div className="cm-footer">
                            <button className="cm-btn-cancel" onClick={() => setPunishConfig(null)}>Cancel</button>
                            <button className="cm-btn-danger" onClick={executePunishment}>Apply {punishConfig.type === 'ban' ? 'Ban' : 'Restriction'}</button>
                        </div>
                    </div>
                </div>
            )}

            {/* Custom Alert Notice */}
            {alertNotice && (
                <div className="custom-modal-overlay">
                    <div className="custom-modal-card">
                        <h3><i className="fas fa-exclamation-circle" style={{color: '#ffab40', marginRight: '8px'}}></i> Notice</h3>
                        <p>{alertNotice}</p>
                        <div className="cm-footer">
                            <button className="cm-btn-primary" onClick={() => setAlertNotice(null)}>Okay</button>
                        </div>
                    </div>
                </div>
            )}

            {/* Custom Disband Modal */}
            {disbandModal && (
                <div className="custom-modal-overlay">
                    <div className="custom-modal-card">
                        <h3 style={{color: '#ff5f5f'}}>Delete Group</h3>
                        <p>This action is irreversible. All messages, files, and links will be permanently deleted.</p>
                        <p style={{fontSize: '0.8rem', color: '#aaa', marginTop: '10px'}}>Type <strong>{chatInfo.title}</strong> to confirm:</p>
                        <input 
                            type="text" 
                            className="cm-text-input" 
                            placeholder={chatInfo.title}
                            value={disbandInput}
                            onChange={e => setDisbandInput(e.target.value)}
                        />
                        <div className="cm-footer" style={{marginTop: '1rem'}}>
                            <button className="cm-btn-cancel" onClick={() => { setDisbandModal(false); setDisbandInput(''); }}>Cancel</button>
                            <button className="cm-btn-danger" onClick={executeDisband} disabled={disbandInput !== chatInfo.title}>Delete Group</button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

const GroupChat = ({ chat, currentUser, onClose, onJoin, isJoining }) => {
    const { user: userProfile } = usePlatform();
    const [messages, setMessages] = useState([]);
    const [input, setInput] = useState('');
    const [members, setMembers] = useState({});
    const [myRole, setMyRole] = useState('member');
    const [activeMenu, setActiveMenu] = useState(null);
    const [isLoading, setIsLoading] = useState(true);
    const [editingMessage, setEditingMessage] = useState(null);
    const [replyingTo, setReplyingTo] = useState(null);

    // Group Hub State
    const [localChatInfo, setLocalChatInfo] = useState({ title: chat.title, avatar_url: chat.avatar_url, metadata: chat.metadata });
    const [isInfoOpen, setIsInfoOpen] = useState(false);
    
    // Moderation State
    const [myMutedUntil, setMyMutedUntil] = useState(null);
    const [deleteConfirm, setDeleteConfirm] = useState(null); // ID of message to delete
    const [kickedNotice, setKickedNotice] = useState(false);
    const [avatarError, setAvatarError] = useState(false);

    // Reset header avatar error state if URL changes
    useEffect(() => setAvatarError(false), [localChatInfo.avatar_url]);

    // Search State
    const [isSearchActive, setIsSearchActive] = useState(false);
    const [searchQuery, setSearchQuery] = useState('');
    const [searchResults, setSearchResults] = useState([]);
    const [currentSearchIndex, setCurrentSearchIndex] = useState(-1);
    const [showSearchList, setShowSearchList] = useState(false);

    const flowRef = useRef(null);

    useEffect(() => {
        const fetchState = async () => {
            // OPTIMIZATION: Fire the heavy queries in parallel instead of sequentially
            const [msgResponse, memResponse, convResponse] = await Promise.all([
                supabase.from('messages')
                    .select('*')
                    .eq('conversation_id', chat.conversation_id)
                    .order('created_at', { ascending: true }),
                supabase.from('conversation_members')
                    .select('user_id, role, muted_until')
                    .eq('conversation_id', chat.conversation_id),
                supabase.from('conversations')
                    .select('title, avatar_url, metadata')
                    .eq('id', chat.conversation_id)
                    .maybeSingle()
            ]);

            if (convResponse.data) {
                setLocalChatInfo(prev => ({
                    ...prev,
                    title: convResponse.data.title,
                    avatar_url: convResponse.data.avatar_url,
                    metadata: convResponse.data.metadata
                }));
            }

            let memMap = {};

            // If we have members, fetch their profile metadata
            if (memResponse.data && memResponse.data.length > 0) {
                const userIds = memResponse.data.map(m => m.user_id);
                
                const { data: profiles } = await supabase
                    .from('profiles')
                    .select('id, full_name, avatar_url')
                    .in('id', userIds);

                memResponse.data.forEach(m => {
                    const prof = profiles?.find(p => p.id === m.user_id);
                    memMap[m.user_id] = { role: m.role, name: prof?.full_name, avatar: prof?.avatar_url };
                    if (m.user_id === currentUser.id) {
                        setMyRole(m.role);
                        setMyMutedUntil(m.muted_until);
                    }
                });
                setMembers(memMap);
            }

            // Immediately set the messages that we fetched concurrently
            if (msgResponse.data) {
                setMessages(msgResponse.data.map(m => ({ ...m, status: 'sent' })));
            }
            
            setIsLoading(false);
        };

        fetchState();

        const channel = supabase.channel(`group_${chat.conversation_id}`)
            .on('postgres_changes', { event: '*', schema: 'public', table: 'messages', filter: `conversation_id=eq.${chat.conversation_id}` }, (payload) => {
                if (payload.eventType === 'INSERT') {
                    setMessages(prev => {
                        if (prev.find(m => m.id === payload.new.id)) return prev;
                        return [...prev, { ...payload.new, status: 'sent' }];
                    });
                } else if (payload.eventType === 'UPDATE') {
                    setMessages(prev => prev.map(m => m.id === payload.new.id ? { ...payload.new, status: 'sent' } : m));
                } else if (payload.eventType === 'DELETE') {
                    setMessages(prev => prev.filter(m => m.id !== payload.old.id));
                }
            })
            .subscribe();

        const memberChannel = supabase.channel(`members_${chat.conversation_id}`)
            .on('postgres_changes', { 
                event: '*', schema: 'public', table: 'conversation_members', filter: `conversation_id=eq.${chat.conversation_id}`
            }, (payload) => {
                if (payload.eventType === 'INSERT') {
                    // Optimistic UI insert to trigger the live counter instantly
                    setMembers(prev => ({...prev, [payload.new.user_id]: { role: payload.new.role, name: 'Loading...', avatar: '' }}));
                    
                    // Fetch real profile silently in background
                    supabase.from('profiles').select('full_name, avatar_url').eq('id', payload.new.user_id).maybeSingle()
                        .then(({data}) => {
                            if (data) {
                                setMembers(prev => ({...prev, [payload.new.user_id]: { role: payload.new.role, name: data.full_name, avatar: data.avatar_url }}));
                            }
                        });
                } else if (payload.eventType === 'UPDATE') {
                    if (payload.new.user_id === currentUser.id) {
                        setMyMutedUntil(payload.new.muted_until);
                        setMyRole(payload.new.role);
                    } else {
                        setOtherReadAt(payload.new.last_read_at);
                        setMembers(prev => ({...prev, [payload.new.user_id]: { ...prev[payload.new.user_id], role: payload.new.role }}));
                    }
                } else if (payload.eventType === 'DELETE') {
                    if (payload.old.user_id === currentUser.id) {
                        setKickedNotice(true);
                    } else {
                        setMembers(prev => {
                            const next = {...prev};
                            delete next[payload.old.user_id];
                            return next;
                        });
                    }
                }
            })
            .subscribe();

        return () => {
            supabase.removeChannel(channel);
            supabase.removeChannel(memberChannel);
        };
    }, [chat.conversation_id]);

    useEffect(() => {
        if (flowRef.current && !isSearchActive) {
            flowRef.current.scrollTop = flowRef.current.scrollHeight;
        }
    }, [messages, isSearchActive]);
    
    const executeSearch = (query) => {
        setSearchQuery(query);
        if (!query.trim()) {
            setSearchResults([]);
            setCurrentSearchIndex(-1);
            return;
        }
        const term = query.toLowerCase();
        // Reverse array so newest messages (bottom) are index 0
        const results = messages.filter(m => m.text && m.text.toLowerCase().includes(term)).reverse();
        setSearchResults(results);
        if (results.length > 0) {
            setCurrentSearchIndex(0);
            scrollToMessage(results[0].id);
        } else {
            setCurrentSearchIndex(-1);
        }
    };

    const searchOlder = () => {
        if (searchResults.length === 0) return;
        let newIdx = currentSearchIndex + 1;
        if (newIdx >= searchResults.length) newIdx = 0; // Wrap around
        setCurrentSearchIndex(newIdx);
        scrollToMessage(searchResults[newIdx].id);
    };

    const searchNewer = () => {
        if (searchResults.length === 0) return;
        let newIdx = currentSearchIndex - 1;
        if (newIdx < 0) newIdx = searchResults.length - 1; // Wrap around
        setCurrentSearchIndex(newIdx);
        scrollToMessage(searchResults[newIdx].id);
    };

    const getSnippet = (text, query) => {
        if (!query) return text;
        const idx = text.toLowerCase().indexOf(query.toLowerCase());
        if (idx === -1) return text;
        const start = Math.max(0, idx - 40);
        const end = Math.min(text.length, idx + query.length + 60);
        let snippet = text.substring(start, end);
        if (start > 0) snippet = '...' + snippet;
        if (end < text.length) snippet = snippet + '...';
        return snippet;
    };

    const handleSend = async () => {
        if (!input.trim()) return;
        const msgText = input;
        setInput('');

        // Handle Edit
        if (editingMessage) {
            setMessages(prev => prev.map(m => m.id === editingMessage.id ? { ...m, text: msgText, is_edited: true } : m));
            await supabase.from('messages').update({ text: msgText, is_edited: true }).eq('id', editingMessage.id);
            setEditingMessage(null);
            return;
        }

        const currentReplyId = replyingTo?.id;
        setReplyingTo(null);

        // Optimistic UI temp message
        const tempId = `temp-${Date.now()}`;
        setMessages(prev => [...prev, {
            id: tempId, conversation_id: chat.conversation_id,
            sender_id: currentUser.id, text: msgText,
            reply_to_id: currentReplyId,
            created_at: new Date().toISOString(), status: 'pending'
        }]);

        const { data } = await supabase.from('messages').insert({
            conversation_id: chat.conversation_id,
            sender_id: currentUser.id,
            text: msgText,
            reply_to_id: currentReplyId
        }).select().maybeSingle();

        if (data) {
            setMessages(prev => prev.map(m => m.id === tempId ? { ...data, status: 'sent' } : m));
        }
    };

    const deleteMessage = (msgId) => {
        setDeleteConfirm(msgId);
        setActiveMenu(null);
    };

    const confirmAndDelete = async () => {
        if (!deleteConfirm) return;
        const msgId = deleteConfirm;
        setDeleteConfirm(null);
        
        console.group(`[Squad:Chat] Executing DELETE for node: ${msgId}`);
        const msgToDelete = messages.find(m => m.id === msgId);
        
        // 1. Optimistic UI removal
        setMessages(prev => prev.filter(m => m.id !== msgId));
        
        try {
            // 2. Storage Cleanup
            if (msgToDelete?.attachments && msgToDelete.attachments.length > 0) {
                const paths = msgToDelete.attachments.map(att => att.path).filter(Boolean);
                if (paths.length > 0) {
                    await supabase.storage.from('chat_media').remove(paths);
                }
            }
            // 3. Database Deletion
            await supabase.from('messages').delete().eq('id', msgId);
        } catch (err) {
            console.error("[Squad:Chat] Deletion failed:", err);
        }
        console.groupEnd();
    };

    const handleCopy = (text) => {
        navigator.clipboard.writeText(text);
        setActiveMenu(null);
    };

    const startEditing = (msg) => {
        setEditingMessage(msg);
        setInput(msg.text);
        setActiveMenu(null);
    };

    const startReply = (msg) => {
        setReplyingTo(msg);
        setActiveMenu(null);
    };

    const scrollToMessage = (id) => {
        const el = document.getElementById(`sq-msg-${id}`);
        if (!el) return;
        el.scrollIntoView({ behavior: 'smooth', block: 'center' });
        el.classList.add('squad-msg-highlight-flash');
        setTimeout(() => el.classList.remove('squad-msg-highlight-flash'), 2500);
    };

    const formatTime = (isoString) => {
        if (!isoString) return '';
        return new Date(isoString).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    };

    const isMember = !!members[currentUser.id];

    return (
        <div className="squad-chat-overlay" onTouchStart={e => e.stopPropagation()}>
            <div className="ambient-prism-light"></div>

            {kickedNotice && (
                <div className="kicked-overlay">
                    <i className="fas fa-user-slash"></i>
                    <h2>Access Revoked</h2>
                    <p>You have been removed or banned from this group by an administrator.</p>
                    <button className="cm-btn-primary" onClick={onClose}>Return to Hub</button>
                </div>
            )}

            {isSearchActive ? (
                <header className="chat-search-header">
                    <button className="icon-button back-btn" onClick={() => { setIsSearchActive(false); setSearchQuery(''); }}><i className="fas fa-arrow-left"></i></button>
                    <div className="chat-search-input-wrapper">
                        <input 
                            type="text" 
                            className="chat-search-input" 
                            value={searchQuery} 
                            onChange={(e) => executeSearch(e.target.value)} 
                            placeholder="Search..." 
                            autoFocus 
                        />
                        <span className="search-count">
                            {searchResults.length > 0 ? `${currentSearchIndex + 1}/${searchResults.length}` : '0/0'}
                        </span>
                    </div>
                    <div className="chat-search-nav">
                        <button onClick={searchOlder} disabled={searchResults.length === 0}><i className="fas fa-chevron-up"></i></button>
                        <button onClick={searchNewer} disabled={searchResults.length === 0}><i className="fas fa-chevron-down"></i></button>
                        <button className="snippet-btn" onClick={() => setShowSearchList(true)} disabled={searchResults.length === 0}><i className="fas fa-list"></i></button>
                    </div>
                </header>
            ) : (
                <header className="squad-header" style={{ justifyContent: 'flex-start', gap: '1.2rem' }}>
                    <button className="icon-button back-btn" onClick={onClose}><i className="fas fa-chevron-left"></i></button>
                    <div className="squad-contact-profile" onClick={() => setIsInfoOpen(true)} style={{cursor: 'pointer'}}>
                        <div className="squad-avatar-ring">
                            {localChatInfo.avatar_url && !avatarError ? (
                                <img src={localChatInfo.avatar_url} alt="Squad Avatar" onError={() => setAvatarError(true)} />
                            ) : (
                                <div className="squad-default-avatar"><i className="fas fa-users"></i></div>
                            )}
                        </div>
                        <div className="squad-header-info">
                            <h2>{localChatInfo.title}</h2>
                            <div className="squad-meta-tags">
                                <span className="squad-badge focus">{localChatInfo.metadata?.focus || 'General'}</span>
                                <span className="squad-badge count"><i className="fas fa-user"></i> {Object.keys(members).length}</span>
                            </div>
                        </div>
                    </div>
                    <button className="icon-button" style={{marginLeft: 'auto'}} onClick={() => setIsSearchActive(true)}><i className="fas fa-search"></i></button>
                </header>
            )}

            <main className="squad-flow" ref={flowRef} onClick={() => setActiveMenu(null)} onScroll={() => setActiveMenu(null)}>
                {isLoading ? (
                    <div className="squad-loading-state">
                        <i className="fas fa-circle-notch fa-spin"></i>
                        <p>Syncing Squad comms...</p>
                    </div>
                ) : messages.length === 0 ? (
                    <div className="squad-empty-state">
                        <i className="fas fa-user-group"></i>
                        <p>{chat.is_preview && !isMember ? "No messages yet. Join to start the discussion!" : "No messages yet. Start the discussion!"}</p>
                    </div>
                ) : (
                    messages.map(m => {
                        const isMine = m.sender_id === currentUser.id;
                        const isDeletedAccount = !m.sender_id;
                        const sender = isDeletedAccount 
                            ? { name: 'Deleted Account', role: 'member' } 
                            : (members[m.sender_id] || { name: 'Unknown User', role: 'member' });
                        const isMenuOpen = activeMenu?.msg?.id === m.id;
                        
                        const repliedMsg = m.reply_to_id ? messages.find(msg => msg.id === m.reply_to_id) : null;
                        const isMissingReply = m.reply_to_id && !repliedMsg;

                        return (
                            <div 
                                key={m.id} 
                                id={`sq-msg-${m.id}`}
                                className={`squad-msg-group ${isMine ? 'mine' : 'theirs'}`} 
                                style={{ zIndex: isMenuOpen ? 100 : 1 }}
                                onClick={(e) => {
                                    e.stopPropagation();
                                    if (chat.is_preview) return; // Read-only context for preview
                                    if (isMenuOpen) {
                                        setActiveMenu(null);
                                        return;
                                    }
                                    
                                    let x = e.clientX || (e.touches && e.touches[0].clientX);
                                    let y = e.clientY || (e.touches && e.touches[0].clientY);
                                    
                                    if (!x || !y) {
                                        const rect = e.currentTarget.getBoundingClientRect();
                                        x = rect.left + rect.width / 2;
                                        y = rect.top + rect.height / 2;
                                    }
                                    
                                    const menuW = 160;
                                    const menuH = 200;
                                    
                                    if (x + menuW > window.innerWidth - 20) x = window.innerWidth - menuW - 20;
                                    if (y + menuH > window.innerHeight - 80) y = window.innerHeight - menuH - 80;
                                    if (y < 80) y = 80;
                                    
                                    setActiveMenu({ msg: m, isMine, x, y });
                                }}
                            >
                                {!isMine && (
                                    <img src={sender.avatar || 'https://via.placeholder.com/150'} alt="Avatar" className="squad-msg-avatar" />
                                )}
                                <div className="squad-bubble-wrapper">
                                    {!isMine && (
                                        <div className="squad-sender-name">
                                            {sender.name}
                                            {sender.role === 'owner' && <i className="fas fa-crown admin-crown"></i>}
                                        </div>
                                    )}
                                    <div className="squad-bubble">
                                    {repliedMsg ? (
                                        <div className="squad-reply-quote" onClick={(e) => { e.stopPropagation(); scrollToMessage(m.reply_to_id); }}>
                                            <div className="sq-quote-content">
                                                <div className="sq-quote-user">
    {!repliedMsg.sender_id ? 'Deleted Account' : (members[repliedMsg.sender_id]?.name || 'Unknown User')}
</div>
                                                <div className="sq-quote-text">{repliedMsg.text}</div>
                                            </div>
                                        </div>
                                    ) : isMissingReply ? (
                                        <div className="squad-reply-quote is-deleted">
                                            <div className="sq-quote-content">
                                                <div className="sq-quote-user">System</div>
                                                <div className="sq-quote-text"><i>Original message deleted</i></div>
                                            </div>
                                        </div>
                                    ) : null}
                                    
                                    {m.text}
                                    
                                    <div className={`squad-time-meta ${isMine ? 'mine-meta' : ''}`}>
                                        {m.is_edited && <span>edited</span>}
                                        {formatTime(m.created_at)}
                                        {isMine && (m.status === 'pending' ? <i className="fa-solid fa-clock" style={{fontSize: '0.6rem'}}></i> : <i className="fa-solid fa-check"></i>)}
                                    </div>
                                </div>
                                </div>
                            </div>
                        );
                    })
                )}
            </main>

            {activeMenu && (
                <div className="squad-ctx-menu" style={{ left: activeMenu.x, top: activeMenu.y }}>
                    {!activeMenu.isMine && (
                        <button className="squad-ctx-btn" onClick={() => startReply(activeMenu.msg)}>
                            <i className="fa-solid fa-reply"></i> Reply
                        </button>
                    )}
                    {activeMenu.msg.text && (
                        <button className="squad-ctx-btn" onClick={() => handleCopy(activeMenu.msg.text)}>
                            <i className="fa-solid fa-copy"></i> Copy Text
                        </button>
                    )}
                    {activeMenu.isMine && (
                        <button className="squad-ctx-btn" onClick={() => startEditing(activeMenu.msg)}>
                            <i className="fa-solid fa-pen"></i> Edit
                        </button>
                    )}
                    {(activeMenu.isMine || myRole === 'owner' || myRole === 'admin') && (
                        <button className="squad-ctx-btn delete" onClick={() => { setDeleteConfirm(activeMenu.msg.id); setActiveMenu(null); }}>
                            <i className="fa-solid fa-trash"></i> {activeMenu.isMine ? 'Delete' : 'Admin Delete'}
                        </button>
                    )}
                </div>
            )}

            <footer className="squad-input-area" style={{ padding: '0 1.5rem calc(1rem + env(safe-area-inset-bottom))', background: 'linear-gradient(to top, #08080c 80%, transparent)' }}>
                {chat.is_preview && !isMember ? (
                    <button className="squad-join-full-btn" onClick={() => onJoin(chat.conversation_id)} disabled={isJoining}>
                        {isJoining ? <i className="fas fa-circle-notch fa-spin"></i> : 'Join Squad'}
                    </button>
                ) : (
                    <>
                        {editingMessage && (
                            <div className="squad-input-mode-header edit-mode">
                                <div className="mode-border"></div>
                                <div className="squad-mode-icon"><i className="fa-solid fa-pen"></i></div>
                                <div className="mode-info">
                                    <span className="mode-user">Editing message</span>
                                    <span className="mode-text">{editingMessage.text}</span>
                                </div>
                                <button className="icon-button" onClick={() => { setEditingMessage(null); setInput(''); }}>
                                    <i className="fa-solid fa-times"></i>
                                </button>
                            </div>
                        )}
                        {replyingTo && (
                            <div className="squad-input-mode-header">
                                <div className="mode-border"></div>
                                <div className="mode-info" onClick={() => scrollToMessage(replyingTo.id)}>
                                    <span className="mode-user">
            Replying to {!replyingTo.sender_id ? 'Deleted Account' : (members[replyingTo.sender_id]?.name || 'Unknown User')}
        </span>
                                    <span className="mode-text">{replyingTo.text}</span>
                                </div>
                                <button className="icon-button" onClick={() => setReplyingTo(null)}>
                                    <i className="fa-solid fa-times"></i>
                                </button>
                            </div>
                        )}
                        
                        {myMutedUntil && new Date(myMutedUntil) > new Date() ? (
                            <div className="squad-muted-notice">
                                <i className="fas fa-microphone-slash"></i>
                                {new Date(myMutedUntil).getFullYear() > 2100 ? "You have been permanently restricted from posting." : `You are restricted from posting until ${new Date(myMutedUntil).toLocaleString()}.`}
                            </div>
                        ) : (
                            <div className="squad-dock">
                                <input 
                                    type="text" 
                                    placeholder="Squad message..." 
                                    value={input} 
                                    onChange={e => setInput(e.target.value)} 
                                    onKeyPress={e => e.key === 'Enter' && handleSend()} 
                                />
                                <button className="squad-send-btn" onClick={handleSend} disabled={!input.trim()}>
                                    <i className={`fa-solid ${editingMessage ? 'fa-check' : 'fa-arrow-up'}`}></i>
                                </button>
                            </div>
                        )}
                    </>
                )}
            </footer>

            {/* Generic Message Delete Confirm Modal */}
            {deleteConfirm && (
                <div className="custom-modal-overlay">
                    <div className="custom-modal-card">
                        <h3>Delete Message</h3>
                        <p>Are you sure you want to permanently delete this message for everyone?</p>
                        <div className="cm-footer">
                            <button className="cm-btn-cancel" onClick={() => setDeleteConfirm(null)}>Cancel</button>
                            <button className="cm-btn-danger" onClick={confirmAndDelete}>Purge Message</button>
                        </div>
                    </div>
                </div>
            )}
            {showSearchList && (
                <div className="chat-search-modal-overlay" onClick={() => setShowSearchList(false)}>
                    <div className="chat-search-modal" onClick={e => e.stopPropagation()}>
                        <div className="csm-header">
                            <h3>Search Results</h3>
                            <button className="icon-button" onClick={() => setShowSearchList(false)}><i className="fas fa-times"></i></button>
                        </div>
                        <div className="csm-body">
                            {searchResults.length === 0 ? (
                                <div className="csm-empty">No matching records found.</div>
                            ) : searchResults.map((m, idx) => (
                                <div key={m.id} className="csm-snippet-card" onClick={() => {
                                    setCurrentSearchIndex(idx);
                                    setShowSearchList(false);
                                    scrollToMessage(m.id);
                                }}>
                                    <div className="csm-meta">
                                        <span>{m.sender_id === currentUser.id ? 'You' : (members[m.sender_id]?.name || 'User')}</span>
                                        <span>{formatTime(m.created_at)}</span>
                                    </div>
                                                                <div className="csm-text">
                                {getSnippet(m.text, searchQuery).split(new RegExp(`(${searchQuery})`, 'gi')).map((part, i) => 
                                    part.toLowerCase() === searchQuery.toLowerCase() ? 
                                    <span key={i} className="csm-highlight">{part}</span> : part
                                )}
                            </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
            
            {isInfoOpen && (
                <GroupInfoPanel 
                    chatInfo={localChatInfo}
                    conversationId={chat.conversation_id}
                    currentUser={currentUser}
                    members={members}
                    setMembers={setMembers}
                    messages={messages}
                    myRole={myRole}
                    onClose={() => setIsInfoOpen(false)}
                    onUpdateInfo={setLocalChatInfo}
                    onDisband={onClose}
                />
            )}
        </div>
    );
};
export default GroupChat;