import React, { useState, useEffect } from 'react';
import { supabase } from '@linkup-platform/sdk-core';
import { usePhoneCheck } from './hooks/usePhoneCheck.js';
import './Auth.css';

const Auth = () => {
    const [isSignUp, setIsSignUp] = useState(false);
    const [isForgotPassword, setIsForgotPassword] = useState(false);
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [fullName, setFullName] = useState('');
    const [phone, setPhone] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);
    const [notice, setNotice] = useState(null); // { title, message, type, actionLabel }
    const [verifyingToken, setVerifyingToken] = useState(false);

    const { status: phoneStatus } = usePhoneCheck(phone, '');

    // Intercept Telegram Token
    useEffect(() => {
        const params = new URLSearchParams(window.location.search);
        const token = params.get('auth_token');
        if (token) {
            setVerifyingToken(true);
            
            // Clean URL visually so they can safely bookmark/share it later
            const cleanUrl = window.location.protocol + "//" + window.location.host + window.location.pathname;
            window.history.replaceState({path: cleanUrl}, '', cleanUrl);

            // Call Edge Function via secure Gateway
            fetch('https://linkup-gateway.getyeteklu2.workers.dev/functions/v1/telegram-auth', {
                method: 'POST',
                headers: { 
                    'Content-Type': 'application/json', 
                    'apikey': 'plt_pub_1a99f3c4d5e68d9e0a2f8d73b', 
                    'x-linkup-client': 'linkup-secure-client-2026' 
                },
                body: JSON.stringify({ auth_token: token })
            })
            .then(res => res.json())
            .then(data => {
                if (data.action_link) {
                    window.location.href = data.action_link; // Hands off to Supabase magic login redirect
                } else {
                    if (data.error === "PHONE_ALREADY_TAKEN") {
                        setVerifyingToken(false);
                        setNotice({
                            title: "Phone Number Already Linked",
                            message: "This phone number is already registered to an existing account. Please sign in with your email and password instead.",
                            type: "exists",
                            actionLabel: "Okay"
                        });
                    } else {
                        throw new Error(data.error || "Invalid link");
                    }
                }
            })
            .catch(err => {
                setVerifyingToken(false);
                const isPhoneTaken = err.message && (
                    err.message.includes('PHONE_ALREADY_TAKEN') ||
                    err.message.includes('profiles_phone_unique') ||
                    err.message.includes('profiles_phone_key') ||
                    err.message.includes('violates unique constraint')
                );

                if (isPhoneTaken) {
                    setNotice({
                        title: "Phone Number Already Linked",
                        message: "This phone number is already registered to an existing account. Please sign in with your email and password instead.",
                        type: "exists",
                        actionLabel: "Okay"
                    });
                } else {
                    setNotice({ title: "Link Expired", message: err.message, type: "error", actionLabel: "Okay" });
                }
            });
        }
    }, []);

    const getBasePath = () => {
        let path = window.location.origin + window.location.pathname;
        // Fix for Blob URLs generated by the IDE Preview environment
        if (window.location.href.startsWith('blob:')) {
            try { path = window.top.location.origin + window.top.location.pathname; } 
            catch (e) { path = window.location.origin + '/'; }
        }
        return path;
    };

    const handleForgotPassword = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError(null);
        try {
            const { error } = await supabase.auth.resetPasswordForEmail(email.toLowerCase().trim(), {
                redirectTo: getBasePath()
            });
            if (error) throw error;
            setNotice({
                title: 'Recovery Link Sent',
                message: 'Check your email inbox for the password reset link.',
                type: 'success',
                actionLabel: 'Back to Sign In'
            });
            setIsForgotPassword(false);
        } catch (err) {
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    const handleGoogleAuth = async () => {
        try {
            setError(null);
            
            // Send OAuth flow back to exactly where the user is (Handles IDE or GitHub subfolders)
            const targetRedirect = getBasePath() + '?conduit_oauth=true';

            const { data, error } = await supabase.auth.signInWithOAuth({
                provider: 'google',
                options: {
                    redirectTo: targetRedirect,
                    skipBrowserRedirect: true
                }
            });
            if (error) throw error;
            
            if (data?.url) {
                // Open as a focused popup window to keep the context linked (window.opener)
                const width = 500;
                const height = 700;
                const left = (window.screen.width / 2) - (width / 2);
                const top = (window.screen.height / 2) - (height / 2);
                window.open(data.url, 'conduit_oauth', `width=${width},height=${height},left=${left},top=${top}`);
            }
        } catch (err) {
            setError(err.message);
        }
    };

    const handleEmailAuth = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError(null);

        try {
            if (isSignUp) {
                // 1. Pre-check: Does this email already exist?
                const { data: checkData, error: checkError } = await supabase.rpc('check_email_provider', { 
                    req_email: email.toLowerCase().trim() 
                });

                if (!checkError && checkData && checkData[0]?.email_exists) {
                    const provider = checkData[0].provider;
                    if (provider === 'google') {
                        setNotice({
                            title: 'Linked via Google',
                            message: 'This email is already associated with a Google account. Please use the Google button to sign in.',
                            type: 'google',
                            actionLabel: 'Got it'
                        });
                        setLoading(false);
                        return;
                    } else {
                        setNotice({
                            title: 'Already a Member',
                            message: 'An account with this email already exists. Would you like to sign in instead?',
                            type: 'exists',
                            actionLabel: 'Switch to Sign In'
                        });
                        setLoading(false);
                        return;
                    }
                }

                // 1b. Phone Uniqueness Pre-Check & Normalization
                let normalizedPhone = phone.replace(/\s+/g, '');
                if (normalizedPhone) {
                    if (!normalizedPhone.startsWith('+')) {
                        if (normalizedPhone.startsWith('0')) {
                            normalizedPhone = '+251' + normalizedPhone.substring(1);
                        } else {
                            normalizedPhone = '+' + normalizedPhone;
                        }
                    }

                    const { data: phoneCheckData, error: phoneError } = await supabase.rpc('check_phone_link_status', { 
                        req_phone: normalizedPhone 
                    });

                    if (!phoneError && phoneCheckData?.exists) {
                        setNotice({
                            title: 'Phone Already Linked',
                            message: phoneCheckData.is_transient 
                                ? 'This phone number is linked to a temporary guest profile. Please use the Telegram login button to merge it.' 
                                : `This phone number is linked to an active account (${phoneCheckData.masked_email}). Please log in using the Telegram button.`,
                            type: 'exists',
                            actionLabel: 'Okay'
                        });
                        setLoading(false);
                        return;
                    }
                }

                // 2. Fresh Sign Up with Normalized Phone
                const { error: signUpError } = await supabase.auth.signUp({
                    email,
                    password,
                    options: { data: { full_name: fullName, phone: normalizedPhone } }
                });
                if (signUpError) throw signUpError;
                
                setNotice({
                    title: 'Verification Sent',
                    message: 'We have dispatched a secure verification link to your email. Please verify your account in your inbox first, then return here to sign in and set up your academic profile.',
                    type: 'success',
                    actionLabel: 'Go to Sign In',
                    action: 'signin'
                });
            } else {
                // Standard Sign-In
                const { error: signInError } = await supabase.auth.signInWithPassword({
                    email,
                    password,
                });
                if (signInError) throw signInError;
            }
        } catch (err) {
            const isPhoneConflict = err.message && (
                err.message.includes('profiles_phone_unique') || 
                err.message.includes('profiles_phone_key') || 
                err.message.includes('saving new user') ||
                err.message.includes('violates unique constraint')
            );

            if (isPhoneConflict) {
                setNotice({
                    title: 'Phone Already Linked',
                    message: 'This phone number is already verified and linked to another account. Please use the Telegram login button instead.',
                    type: 'exists',
                    actionLabel: 'Okay'
                });
            } else {
                setError(err.message);
            }
        } finally {
            setLoading(false);
        }
    };

    // The Escape View Check (Blocks Telegram's isolated In-App Browser)
    const isTelegramWebView = navigator.userAgent.includes('Telegram');
    
    if (isTelegramWebView) {
        return (
            <div className="auth-root" style={{ flexDirection: 'column' }}>
                <div className="ambient-elegant-bg"></div>
                <div className="webview-escape-card">
                    <i className="fab fa-safari" style={{ fontSize: '3rem', color: '#42d7b8', marginBottom: '1rem' }}></i>
                    <h2 style={{ marginBottom: '1rem', color: '#fff', fontSize: '1.4rem' }}>Open in Browser</h2>
                    <p style={{ color: '#aaa', lineHeight: 1.5, fontSize: '0.9rem' }}>
                        Telegram's built-in browser cannot save your secure session. <br/><br/>
                        Please tap the <strong>three dots (⋮)</strong> at the top right of your screen and select <strong>"Open in Chrome"</strong> or <strong>"Open in Safari"</strong>.
                    </p>
                </div>
            </div>
        );
    }

    if (verifyingToken) {
        return (
            <div className="auth-root" style={{ flexDirection: 'column' }}>
                <div className="ambient-elegant-bg"></div>
                <i className="fas fa-circle-notch fa-spin" style={{ fontSize: '2.5rem', color: '#42d7b8', zIndex: 10 }}></i>
                <h2 style={{ zIndex: 10, marginTop: '1rem', fontWeight: 600, color: '#fff' }}>Securing Connection...</h2>
            </div>
        );
    }

    return (
        <div className="auth-root">
            <div className="ambient-elegant-bg"></div>

            {notice && (
                <div className="auth-notice-overlay" onClick={() => setNotice(null)}>
                    <div className="auth-notice-card" onClick={e => e.stopPropagation()}>
                        <div className={`notice-icon ${notice.type}`}>
                            {notice.type === 'google' && <i className="fab fa-google"></i>}
                            {notice.type === 'exists' && <i className="fas fa-user-check"></i>}
                            {notice.type === 'success' && <i className="fas fa-paper-plane"></i>}
                        </div>
                        <h2>{notice.title}</h2>
                        <p>{notice.message}</p>
                        <button className="notice-btn" onClick={() => {
                            if (notice.type === 'exists' || notice.action === 'signin') {
                                setIsSignUp(false);
                            }
                            setNotice(null);
                        }}>
                            {notice.actionLabel}
                        </button>
                    </div>
                </div>
            )}
            
            <div className="auth-card">
                <header className="auth-header">
                    <h1 className="auth-title">{isForgotPassword ? 'Reset Password' : 'LinkUp'}</h1>
                    <p className="auth-subtitle">
                        {isForgotPassword 
                            ? 'Enter your email to receive a recovery link.' 
                            : isSignUp ? 'Create an account to get started' : 'Welcome back, please sign in'}
                    </p>
                </header>

                {error && <div className="auth-error">{error}</div>}

                <form onSubmit={isForgotPassword ? handleForgotPassword : handleEmailAuth}>
                    {!isForgotPassword && (
                        <div className={`input-group dynamic-field ${isSignUp ? 'is-visible' : ''}`}>
                            <input 
                                type="text" 
                                className="auth-input" 
                                placeholder="Full Name" 
                                value={fullName}
                                onChange={(e) => setFullName(e.target.value)}
                                required={isSignUp}
                            />
                            <i className="fas fa-user input-icon"></i>
                        </div>
                    )}

                    <div className="input-group">
                        <input 
                            type="email" 
                            className="auth-input" 
                            placeholder="Email address" 
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            required
                        />
                        <i className="fas fa-envelope input-icon"></i>
                    </div>

                    {isSignUp && !isForgotPassword && (
                        <>
                            <div className="input-group">
                                <input 
                                    type="tel" 
                                    className="auth-input" 
                                    placeholder="Phone (e.g. 0912...)" 
                                    value={phone}
                                    onChange={(e) => setPhone(e.target.value)}
                                    required
                                    style={phoneStatus === 'taken' || phoneStatus === 'invalid' ? { borderColor: '#ff5f5f' } : (phoneStatus === 'available' ? { borderColor: 'var(--accent-teal)' } : {})}
                                />
                                <i className="fas fa-phone input-icon" style={phoneStatus === 'taken' || phoneStatus === 'invalid' ? { color: '#ff5f5f' } : (phoneStatus === 'available' ? { color: 'var(--accent-teal)' } : {})}></i>
                                {phone !== '' && phoneStatus !== 'idle' && (
                                    <div style={{marginTop: '6px', fontSize: '0.75rem', fontWeight: 500, color: (phoneStatus === 'taken' || phoneStatus === 'invalid') ? '#ff5f5f' : 'var(--accent-teal)', display: 'flex', alignItems: 'center', gap: '6px', paddingLeft: '4px'}}>
                                        {phoneStatus === 'checking' && <><i className="fas fa-circle-notch fa-spin"></i> Checking availability...</>}
                                        {phoneStatus === 'invalid' && <><i className="fas fa-exclamation-circle"></i> Enter a valid Ethiopian phone number.</>}
                                        {phoneStatus === 'taken' && <><i className="fas fa-times-circle"></i> This phone number is already registered.</>}
                                        {phoneStatus === 'error' && <><i className="fas fa-exclamation-triangle"></i> Connection error.</>}
                                        {phoneStatus === 'available' && <><i className="fas fa-check-circle"></i> Phone number available.</>}
                                    </div>
                                )}
                            </div>
                            <div className="commitment-note">
                                <i className="fas fa-shield-halved"></i>
                                <p><strong>Secure Identity:</strong> Please provide an accurate number. It is used for <strong>rewards</strong>, account recovery, and regional study groups.</p>
                            </div>
                        </>
                    )}

                    {!isForgotPassword && (
                        <>
                            <div className="input-group">
                                <input 
                                    type="password" 
                                    className="auth-input" 
                                    placeholder="Password" 
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                    required
                                />
                                <i className="fas fa-lock input-icon"></i>
                            </div>
                            {!isSignUp && (
                                <div style={{ textAlign: 'right', marginBottom: '1rem' }}>
                                    <button type="button" style={{ background: 'none', border: 'none', color: '#888', fontSize: '0.8rem', cursor: 'pointer', fontFamily: 'Poppins', fontWeight: '500' }} onClick={() => setIsForgotPassword(true)}>
                                        Forgot Password?
                                    </button>
                                </div>
                            )}
                        </>
                    )}

                    <button type="submit" className="auth-submit-btn" disabled={loading || (isSignUp && !isForgotPassword && (phoneStatus === 'taken' || phoneStatus === 'invalid' || phoneStatus === 'checking'))}>
                        {loading ? <i className="fas fa-circle-notch fa-spin"></i> : (isForgotPassword ? 'Send Link' : isSignUp ? 'Sign Up' : 'Sign In')}
                    </button>
                </form>

                {!isForgotPassword ? (
                    <>
                        <div className="auth-divider">
                            <span>Or continue with</span>
                        </div>

                        <button className="google-btn" onClick={handleGoogleAuth} type="button">
                            <svg className="google-icon" viewBox="0 0 24 24">
                                <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                                <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                                <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                                <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
                            </svg>
                            Google
                        </button>

                        <button className="telegram-btn" type="button" onClick={() => {
                            window.open('https://t.me/linkupregistrationbot', '_blank', 'noopener,noreferrer');
                        }}>
                            <i className="fab fa-telegram"></i> Log in with Telegram
                        </button>

                        <div className="auth-footer">
                            {isSignUp ? 'Already have an account?' : "Don't have an account?"}
                            <button type="button" onClick={() => setIsSignUp(!isSignUp)}>
                                {isSignUp ? 'Sign In' : 'Sign Up'}
                            </button>
                        </div>
                    </>
                ) : (
                    <div className="auth-footer">
                        <button type="button" onClick={() => setIsForgotPassword(false)}>
                            <i className="fas fa-arrow-left"></i> Back to Sign In
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

export default Auth;