import React, { useState, useEffect, useRef } from 'react';
import { supabase } from '@linkup-platform/sdk-core';
import AvatarCropperModal from '../../../src/core/components/AvatarCropperModal.jsx';
import GroupMembersTab from './GroupMembersTab.jsx';
import GroupMediaTab from './GroupMediaTab.jsx';
import GroupSettingsTab from './GroupSettingsTab.jsx';
import { invokeSocial } from '../api.js';
import './GroupInfoPanel.css';

const GroupInfoPanel = ({ chatInfo, conversationId, currentUser, members, setMembers, messages, myRole, onClose, onUpdateInfo, onDisband, onOpenAdminSettings, onOpenUser }) => {
    const canSeeMembers = myRole === 'owner' || myRole === 'admin' || chatInfo.metadata?.hide_members !== true;
    
    const [activeTab, setActiveTab] = useState(canSeeMembers ? 'members' : 'media');
    
    useEffect(() => {
        if (!canSeeMembers && activeTab === 'members') {
            setActiveTab('media');
        }
    }, [canSeeMembers, activeTab]);
    
    const [selectedFile, setSelectedFile] = useState(null);
    const [croppedAvatar, setCroppedAvatar] = useState(null);
    const fileInputRef = useRef(null);
    
    const [isSaving, setIsSaving] = useState(false);
    const [isProcessing, setIsProcessing] = useState(false);
    const [alertNotice, setAlertNotice] = useState(null);
    const [avatarError, setAvatarError] = useState(false);

    useEffect(() => {
        if (alertNotice?.success) {
            const timer = setTimeout(() => setAlertNotice(null), 3000);
            return () => clearTimeout(timer);
        }
    }, [alertNotice]);

    useEffect(() => setAvatarError(false), [croppedAvatar, chatInfo.avatar_url]);

    const [showOptions, setShowOptions] = useState(false);
    const [showAddMember, setShowAddMember] = useState(false);
    const [activeMemberMenu, setActiveMemberMenu] = useState(null);
    const [inviteCopied, setInviteCopied] = useState(false);

    // Strict DB truth. No front-end guessing.
    const squadHandle = chatInfo.metadata?.slug;
    
    let rawBase = window.location.origin + window.location.pathname;
    // Fix for Blob URLs generated by the IDE Preview environment
    if (window.location.href.startsWith('blob:')) {
        try { 
            rawBase = window.top.location.origin + window.top.location.pathname; 
        } catch (e) { 
            rawBase = window.location.origin + '/'; 
        }
    }
    const cleanBase = rawBase.split('?')[0].replace(/\/$/, '');
    
    const inviteLink = squadHandle ? `${cleanBase}?sq=${squadHandle}` : 'Fetching invitation link...';

    const isPublic = !chatInfo.metadata?.privacy || chatInfo.metadata.privacy === 'public';

    const handleCopyInvite = () => {
        navigator.clipboard.writeText(inviteLink);
        setInviteCopied(true);
        setTimeout(() => setInviteCopied(false), 2000);
    };



    const handleAvatarUpdate = async (blob) => {
        const url = URL.createObjectURL(blob);
        setCroppedAvatar({ blob, url });
        setSelectedFile(null);

        setIsSaving(true);
        try {
            const arrayBuffer = await blob.arrayBuffer();
            const filePath = `group_avatars/${conversationId}/avatar_${Date.now()}.png`;
            const { error: uploadError } = await supabase.storage.from('chat_media').upload(filePath, arrayBuffer, { contentType: 'image/png', upsert: true });
            if (uploadError) throw uploadError;

            const { data: { publicUrl } } = supabase.storage.from('chat_media').getPublicUrl(filePath);
            
            const { error: dbError } = await supabase.from('conversations').update({ avatar_url: publicUrl }).eq('id', conversationId);
            if (dbError) throw dbError;

            onUpdateInfo({ ...chatInfo, avatar_url: publicUrl });
            setAlertNotice({ title: "Success", msg: "Group avatar updated successfully.", success: true });
        } catch (err) {
            console.error("Group avatar update error:", err);
            setAlertNotice({ title: "Update Failed", msg: err.message || "Failed to update group avatar.", success: false });
        } finally {
            setIsSaving(false);
            setCroppedAvatar(null);
        }
    };



    const displayAvatar = croppedAvatar?.url || chatInfo.avatar_url;

    return (
        <div className="si-overlay" onClick={() => { setActiveMemberMenu(null); setShowOptions(false); }}>
            {selectedFile && (
                <AvatarCropperModal 
                    imageFile={selectedFile} 
                    onCancel={() => setSelectedFile(null)} 
                    onSave={handleAvatarUpdate}
                />
            )}
            <div className="si-sheet" onClick={(e) => { e.stopPropagation(); setShowOptions(false); setActiveMemberMenu(null); }}>
                <div className="si-hero">
                    <button className="si-back" onClick={onClose}><i className="fas fa-chevron-left"></i></button>
                    <div className="si-options-wrapper" style={{ display: 'flex', gap: '8px' }}>
                        {myRole === 'owner' && (
                            <button className="si-options" onClick={onOpenAdminSettings} title="Admin Controls">
                                <i className="fas fa-key"></i>
                            </button>
                        )}
                        {(myRole === 'owner' || myRole === 'admin' || chatInfo.metadata?.members_can_add !== false) && (
                            <>
                                <button className="si-options" onClick={(e) => { e.stopPropagation(); setShowOptions(!showOptions); setActiveMemberMenu(null); }}>
                                    <i className="fas fa-ellipsis-v"></i>
                                </button>
                                {showOptions && (
                                    <div className="si-dropdown-menu" style={{top: '40px', right: '0'}}>
                                        <button onClick={() => { setShowOptions(false); setShowAddMember(true); }}><i className="fas fa-user-plus"></i> Add Members</button>
                                    </div>
                                )}
                            </>
                        )}
                    </div>

                    <input type="file" ref={fileInputRef} style={{ display: 'none' }} accept="image/*" onChange={(e) => {
                        if (e.target.files && e.target.files[0]) setSelectedFile(e.target.files[0]);
                        e.target.value = null;
                    }} />
                    <div className="si-avatar-container" onClick={() => myRole === 'owner' && fileInputRef.current?.click()} style={{cursor: myRole === 'owner' ? 'pointer' : 'default'}}>
                        <div className="si-avatar">
                            {displayAvatar && !avatarError ? <img src={displayAvatar} alt="Squad" onError={() => setAvatarError(true)} /> : <i className="fas fa-users"></i>}
                        </div>
                        {myRole === 'owner' && <div className="si-avatar-edit"><i className="fas fa-pencil"></i></div>}
                    </div>
                    <h2 className="si-title">{chatInfo.title}</h2>
                    <div className="si-ppn">#{conversationId.substring(0,8).toUpperCase()}</div>
                    <div className="si-badges">
                        <span className={`si-badge ${!isPublic ? 'private' : 'public'}`}>
                            <i className={`fas fa-${!isPublic ? 'lock' : 'globe'}`}></i> {!isPublic ? 'private' : 'public'}
                        </span>
                        {chatInfo.metadata?.focus && (
                            <span className="si-badge" style={{background: 'rgba(255,255,255,0.1)', color: '#ccc'}}>{chatInfo.metadata.focus}</span>
                        )}
                    </div>

                    {chatInfo.metadata?.bio && (
                        <div className="si-bio-display">
                            {chatInfo.metadata.bio}
                        </div>
                    )}

                    {isPublic && (
                        <div className="si-invite-box">
                            <div className="si-invite-url">{inviteLink}</div>
                            <button className="si-invite-copy-btn" onClick={handleCopyInvite}>
                                {inviteCopied ? <i className="fas fa-check"></i> : <i className="fas fa-copy"></i>}
                            </button>
                        </div>
                    )}
                </div>

                <div className="si-tabs">
                    {canSeeMembers && <div className={`si-tab ${activeTab === 'members' ? 'active' : ''}`} onClick={() => setActiveTab('members')}>Members</div>}
                    <div className={`si-tab ${activeTab === 'media' ? 'active' : ''}`} onClick={() => setActiveTab('media')}>Media</div>
                    {myRole === 'owner' && <div className={`si-tab ${activeTab === 'settings' ? 'active' : ''}`} onClick={() => setActiveTab('settings')}>Control Panel</div>}
                </div>

                <div className="si-body">
                    {activeTab === 'members' && canSeeMembers && (
                        <GroupMembersTab 
                            conversationId={conversationId}
                            currentUser={currentUser}
                            members={members}
                            setMembers={setMembers}
                            myRole={myRole}
                            onOpenUser={onOpenUser}
                            isProcessing={isProcessing}
                            setIsProcessing={setIsProcessing}
                            setAlertNotice={setAlertNotice}
                            showAddMember={showAddMember}
                            setShowAddMember={setShowAddMember}
                            activeMemberMenu={activeMemberMenu}
                            setActiveMemberMenu={setActiveMemberMenu}
                        />
                    )}

                    {activeTab === 'media' && (
                        <GroupMediaTab messages={messages} members={members} />
                    )}

                    {activeTab === 'settings' && myRole === 'owner' && (
                        <GroupSettingsTab 
                            chatInfo={chatInfo}
                            conversationId={conversationId}
                            onUpdateInfo={onUpdateInfo}
                            onDisband={onDisband}
                            isProcessing={isProcessing}
                            setIsProcessing={setIsProcessing}
                            setAlertNotice={setAlertNotice}
                            cleanBase={cleanBase}
                        />
                    )}
                </div>
        </div>
    );
};

export default GroupInfoPanel;